name: 'php-build-win'
on:
  push:
  workflow_dispatch:
jobs:
  php-build-win:
    runs-on: windows-2025
    permissions: write-all
    steps:
      - shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
          c:
          git clone --depth 1 https://github.com/php/php-sdk-binary-tools c:\php-sdk
          cd c:\php-sdk
          echo %cd%
          echo %~dp0
          echo %~dpnx0
          echo "init phpsdk"
          call c:\php-sdk\phpsdk-vs17-x64.bat
          echo "buildtree"
          call c:\php-sdk\bin\phpsdk_buildtree.bat phpmaster
          echo "clone php-src"
          git clone --depth 1 https://github.com/php/php-src php-src
          cd php-src
          echo %cd%
          echo "deps"
          call c:\php-sdk\bin\phpsdk_deps.bat --update --branch master
          echo "buildconf"
          call buildconf.bat
          echo "configure"
          call configure.bat --enable-cli
          echo "nmake"
          nmake
          nmake snap
          dir C:\php-sdk\php-src\Release
          dir C:\php-sdk\php-src\Release_TS
      - env:
         GH_TOKEN: ${{ github.token }}
        run: |
         gh release create "php-release" C:\php-sdk\php-src\Release_TS
            
