name: 'php-build-win'
on:
  push:
  workflow_dispatch:
jobs:
  php-build-win:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - shell: cmd
        run: |
          c:
          git clone --depth 1 https://github.com/php/php-sdk-binary-tools c:\php-sdk
          cd c:\php-sdk
          echo %cd%
          echo %~dp0
          echo %~dpnx0
          echo "init phpsdk"
          phpsdk-vs17-x64.bat
          echo "buildtree"
          phpsdk_buildtree phpmaster
          echo "clone php-src"
          git clone --depth 1 https://github.com/php/php-src php-src
          cd php-src
          echo %cd%
          echo "deps"
          phpsdk_deps --update --branch master
          echo "buildconf"
          buildconf
          echo "configure"
          configure --enable-cli
          echo "nmake"
          nmake
