name: 'php-build-win'
on:
  #push:
  workflow_dispatch:
jobs:
  php-build-win:
    runs-on: windows-2025
    permissions: write-all
    #continue-on-error: true
    steps:
      - shell: cmd
        continue-on-error: true
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          SET PHP_SDK_VS=vs17
          c:
          git clone --quiet --depth 1 https://github.com/php/php-sdk-binary-tools c:\php-sdk
          cd c:\php-sdk
          echo %cd%
          echo %~dp0
          echo %~dpnx0
          echo "init phpsdk"
          call c:\php-sdk\phpsdk-vs17-x64.bat
          echo "buildtree"
          call c:\php-sdk\bin\phpsdk_buildtree.bat phpmaster
          echo "clone php-src"
          git clone --depth 1 https://github.com/php/php-src php-src
          cd php-src
          echo %cd%
          echo "deps"
          call c:\php-sdk\bin\phpsdk_deps.bat --update --branch master
          echo "buildconf"
          call buildconf.bat
          echo "configure"
          call configure.bat --disable-all --enable-cli
          echo "nmake"
          SET PATH = "%PATH%;C:\msys64\usr\bin"
          SET CL=/MP
          wget http://download.qt.io/official_releases/jom/jom.zip
          7z x jom.zip
          jom
          jom snap
          #nmake
          #nmake snap
          dir C:\php-sdk\php-src\x64\Release_TS\php-8.5.0-dev
      - env:
         GH_TOKEN: ${{ github.token }}
        run: |
         set DT=%date:~10,4%-%date:~4,2%-%date:~7,2%_%time:~0,2%-%time:~3,2%-%TIME:~6,2%
         gh release create %DT% C:\php-sdk\php-src\x64\Release_TS\php-8.5.0-dev\php-devel-pack-8.5.0-dev-Win32-vs17-x64.zip
            
